title: Fabien Fivaz
email: fabien.fivaz@unine.ch
description: Conseiller national écolo et de gauche. Biologiste. Neuchâtelois.
url: "http://fabienfivaz.ch"
twitter_username: ffivaz
github_username:  ffivaz

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown

gems:
  - jekyll-redirect-from
