title: Fabien Fivaz
email: fabien.fivaz@unine.ch
description: Biologiste, homme politique écolo et de gauche. Député au Grand Conseil neuchâtelois. Président de StopOGM.
url: "http://fabienfivaz.ch"
twitter_username: ffivaz
github_username:  ffivaz

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown

gems:
  - jekyll-redirect-from